##################################################################################
##################################################################################
###########################                            ###########################
###########################      CustomJoinStream      ###########################
###########################            Автор           ###########################
########################### https://vk.com/id109471660 ###########################
###########################                            ###########################
###########################      Плагин для замены     ###########################
###########################          HideStream        ###########################
###########################                            ###########################
##################################################################################

#Настраиваемые сообщения при входе/выходе, необходимо выдать пермишн customjoinstream.stream
Messages:
    JoinMessage: '&3Игрок&r %prefix &c%nickname &3заходит на сервер'
    QuitMessage: '&3Игрок&r %prefix &c%nickname &3выходит с сервера'


#Возможно будут еще дополнения(но это не точно).