##################################################################################
##################################################################################
###########################                            ###########################
###########################      CustomJoinStream      ###########################
###########################            Автор           ###########################
########################### https://vk.com/id109471660 ###########################
###########################                            ###########################
###########################      Плагин для замены     ###########################
###########################          HideStream        ###########################
###########################                            ###########################
##################################################################################

#Настраиваемые сообщения при входе/выходе, необходимо выдать пермишн costumjoinstream.stream
JoinMessage: '&3Игрок &c%p &3заходит на сервер'
QuitMessage: '&3Игрок &c%p &3выходит с сервера'


#Возможно будут еще дополнения(но это не точно).