##############################
#                            #
#      CustomJoinStream      #
#           Author           #
#           Mr_Krab          #
# https://vk.com/id109471660 #
#                            #
#    HideStream Replacing    #
#                            #
##############################

#Язык используемый плагином, после изменения необходимо ввеси команду /cjs reload
locale: ru_RU
#Кастомные сообщения о входе/выходе игроков, необходимо выдать пермишн customjoinstream.stream
#Для параметров %prefix и %suffix требуется плагин Vault и любой плагин пермишенов, например Pex
Messages:
    JoinMessage: '&3Игрок&r %prefix &c%nickname&r %suffix &3зашел на сервер'
    QuitMessage: '&3Игрок&r %prefix &c%nickname&r %suffix &3вышел с сервера'
#Воспроизведение звука по группам
Groups:
    default: 
        sound: BLOCK_GLASS_BREAK
