##############################
#                            #
#      CustomJoinStream      #
#           Author           #
#           Mr_Krab          #
# https://vk.com/id109471660 #
#                            #
#    HideStream Replacing    #
#                            #
##############################

#Язык используемый плагином, после изменения необходимо ввеси команду /cjs reload
locale: ru_RU
#Кастомные сообщения о входе/выходе игроков, необходимо выдать пермишн customjoinstream.stream
Messages:
    JoinMessage: '&3Игрок&r %prefix &c%nickname &3зашел на сервер'
    QuitMessage: '&3Игрок&r %prefix &c%nickname &3вышел с сервера'