name: CostumJoinStream
main: mr_krab.customjoinstream.Plugin
version: 0.5
author: Mr_Krab
description: '&3Простой самописный плагин'
commands:
   cjs:
      usage: /cjs reload
      permission: customjoinstream.reload
      description: ...